name: Readme Template
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update NPM dependencies      
      run: "npm install"
    - name: Download Template
      working-directory: ./templates 
      run: | 
        curl -H 'Authorization: token ${{ secrets.READMETOKEN }}'  -H 'Accept: application/vnd.github.v3.raw'  -O  -L https://raw.githubusercontent.com/SergeiGolos/sergeigolos.github.io/fix-work-experiance-update-lyric/template/README.md
    - name: Generate README.md
      run: npx ejs-cli --base-dir "templates" --file "README.md"  --options resume.json --out "./"
    - name: Update README.md      
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Auto-update README.md"
          git push
        fi